version: "3"

services:
  pihole:
    container_name: Pi-Hole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      #- 8081:80/tcp
      #- 4443:443/tcp
    environment:
      TZ: Europe/Stockholm
      WEBPASSWORD: password
    # Volumes store your data between container upgrades
    volumes:
      - pihole:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.myhome.grkamalteja.com`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
      #- traefik.http.routers.pihole.entrypoints=pihole
      #- traefik.tcp.routers.pihole.service=pihole
    networks:
      - traefik_default


networks:
  traefik_default:
    external: true

volumes:
  pihole:
    external: true
  pihole_dnsmasq:
    external: true
