version: "3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex

    environment:
      PUID: 1000
      PGID: 1000

    volumes:
      - plex_config:/config
      - plex_music:/Music
      - plex_videos:/Video

    networks:
      - traefik_default

    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.myhome.grkamalteja.com`)
      - traefik.http.services.plex.loadbalancer.server.port=32400

networks:
  traefik_default:
    external: true

volumes:
  plex_config:
    external: true
  plex_music:
    external: true
  plex_videos:
    external: true
